### ISSUE TITLE
How to get unread message count?

### ISSUE THREAD

**Issue by Manibaratam** [DevSurya/ChatApp-Swift-And-Firebase#5]
How to get unread message count?

**Comment by DevSurya** [comment]
This functionality is not yet implemented. Thanks for the open ticket, I will definitely look into.

bdw to implement this you can use below logic.

Step 1:
Fetch the array of message data in the app. store the count of it an userDefault. For E.g:-
`UserDefaults.standard.set(arrMessageData.count, forKey: "messageCount")`

Step:-2 Set Counter-Zero when the message is read Or Appending the old value with the new value

Case:1 Reading the Message
When user opens a chat window to read the conversation then forcefully make the value of my userDefault value to 0

`UserDefaults.standard.set(0, forKey: "messageCount")`

Case:2 If message is un-read
In that case if chat window is not opened then there will be some value in userDefault. In this case First fetch the current count in userDefault and then make the FirbeBase call and get the new count and Add both and then save in the same key.

Note:- The idea of storing the counter in userDefault is used because it can be accessed anywhere in the app and can directly be shown in any label or button.

**Comment by bariksurya** [comment]
This functionality is not yet implemented. Thanks for the open ticket, I will definitely look into.

bdw to implement this you can use below logic.

**Step 1:**
Fetch the array of message data in the app. store the count of it an userDefault. For E.g:-
`UserDefaults.standard.set(arrMessageData.count, forKey: "messageCount")`

**Step 2:**
 Set Counter-Zero when the message is read Or Appending the old value with the new value

**Case:1 Message is read**
When user opens a chat window to read the conversation then forcefully make the value of my userDefault value to 0
`UserDefaults.standard.set(0, forKey: "messageCount")`

**Case:2 If message is un-read**
In that case if chat window is not opened then there will be some value in userDefault. In this case First fetch the current count in userDefault and then make the FirbeBase call and get the new count and Add both and then save in the same key.

Note:- The idea of storing the counter in userDefault is used because it can be accessed anywhere in the app and can directly be shown in any label or button.
